### ISSUE TITLE
ubut 22.04 in wsl

### ISSUE THREAD

**Issue by rejuce** [matheusbach/legen#12]
after install and running it I get:

Traceback (most recent call last):
  File "/home/jk/legen/legen.py", line 10, in <module>
    import translate_utils
  File "/home/jk/legen/translate_utils.py", line 8, in <module>
    import subtitle_utils
  File "/home/jk/legen/subtitle_utils.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

i had to additionally install 
sudo apt-get install python3-tk

**Comment by matheusbach** [comment]
tkinter is a native python lib, so i didn't include in requirements or other complementary step on README.md. WSL probably doesn't come with tkinter because this lib is related to rendering things on screen. Install manually as you have done or use LeGen native in windows
