### ISSUE TITLE
error: wsl v2 - Ubuntu-22.04 

### ISSUE THREAD

**Issue by yakkobr** [matheusbach/legen#13]
PS C:\Users\suporte> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
  Ubuntu-22.04           Running         2
**********************************

command:
python3 legen.py -i legenda --input_lang en --translate pt_BR -ts:m large -ts:d cpu --disable_hardsubs
**********************************

output:
legen v0.16 - github.com/matheusbach/legen
python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Loading whisperx model: large-v3 (auto) on cpu
/home/suporte/ .local/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispat
cher enabled, this function is no-op. You can remove the function call.                                                                                               torchaudio.set_audio_backend("soundfile")
/home/suporte/ .local/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. Wit
h dispatcher enabled, this function is no-op. You can remove the function call.                                                                                       torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
No language specified, language will be first be detected for each audio file (increases inference time).
Traceback (most recent call last):
  File "/home/suporte/ legen/legen.py", line 111, in <module>
    whisper_model = whisperx.load_model(
  File "/home/suporte/ .local/lib/python3.10/site-packages/whisperx/asr.py", line 95, in load_model
    default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
TypeError: TranscriptionOptions.__new__() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold'

**Comment by yakkobr** [comment]
adicionei o parametro:

 -ts:e whisper

**Comment by yakkobr** [comment]
depois que instalei o pacote whisperX (https://github.com/matheusbach/whisperX) removi a tag "-ts:e whisper" e funcionou corretamente
