### ISSUE TITLE
Erro ao executar localmente 

### ISSUE THREAD

**Issue by rdoolfcdev** [matheusbach/legen#17]
Qual seria a solução para rodar localmente, deu erro

FFMPEG Instalado em :

C:\ffmpeg

Arquivos em MP4 ( vídeo ) na pasta  :

C:\Users\rdool\Downloads\spring

Saida do Terminal :

Loading whisperx model: medium (auto) on cpu
C:\Users\rdool\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\rdool\.cache\torch\whisperx-vad-segmentation.bin`
No language specified, language will be first be detected for each audio file (increases inference time).
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.3.1+cpu. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "C:\Users\rdool\legen\legen.py", line 106, in <module>
    with time_task(message_start=f"\nLoading {args.transcription_engine} model: {wblue}{args.transcription_model}{default} ({transcription_compute_type}) on {wblue}{torch_device}{default}", end="\n"):
  File "C:\Users\rdool\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\rdool\legen\utils.py", line 16, in time_task
    print(f"{message} {formatted_elapsed_time}", flush=True)
  File "C:\Users\rdool\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u23f1' in position 0: character maps to <undefined>

**Comment by matheusbach** [comment]
por algum motivo, seu windows não está suportando o caractere unicode ⏱ (relogio de cronometro, caso você não esteja vendo o caractere). Você pode usar o powershell ao invés do CMD ou tentar como metodo paliativo rodar o comando ```chcp 65001``` antes de rodar o legen, todas as vezes que abrir o terminal para isso
